"""empty message

Revision ID: 24508e02a2bb
Revises: bcdf48d944b7
Create Date: 2021-02-12 13:48:00.189919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24508e02a2bb'
down_revision = 'bcdf48d944b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('identity', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklisted_token')
    # ### end Alembic commands ###
