"""empty message

Revision ID: 66367f20df42
Revises: 384c1ab3091e
Create Date: 2021-02-12 15:21:55.071828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66367f20df42'
down_revision = '384c1ab3091e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('university_professor', 'professor_id',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('university_professor', 'professor_id',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###
