"""empty message

Revision ID: da3972a435fa
Revises: 24508e02a2bb
Create Date: 2021-02-12 14:02:37.547858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3972a435fa'
down_revision = '24508e02a2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_token', sa.Column('expires', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklisted_token', 'expires')
    # ### end Alembic commands ###
